language: bash
services: docker

env:
  - VERSION=7 VARIANT=
  - VERSION=6 VARIANT=

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images
# https://github.com/docker-library/elasticsearch/issues/98#issuecomment-254656216
  - sudo sysctl -w vm.max_map_count=262144

before_script:
  - env | sort
  - wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash
  - cd "$VERSION/$VARIANT"
  - image="elasticsearch:${VERSION}${VARIANT:+-$VARIANT}"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t "$image" .
      ~/official-images/test/run.sh "$image"
    )

after_script:
  - docker images

# vim:set et ts=2 sw=2:
